# Generated by Django 5.1.1 on 2024-12-20 02:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_fichadetreino'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='descanso',
            field=models.JSONField(default=dict),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='frequencia',
            field=models.TextField(default=0),
            preserve_default=False,
        ),
    ]
