# Generated by Django 5.1.1 on 2024-12-20 02:27

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_userprofile_descanso_userprofile_frequencia'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='fichadetreino',
            name='usuario',
            field=models.OneToOneField(default=0, on_delete=django.db.models.deletion.CASCADE, related_name='ficha_de_treino', to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
    ]
