# Generated by Django 5.1.1 on 2024-12-20 02:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_fichadetreino_usuario'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fichadetreino',
            name='usuario',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='ficha_de_treino', to='core.userprofile'),
        ),
    ]
