# Generated by Django 5.1.1 on 2024-12-20 02:56

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_alter_fichadetreino_usuario'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='fichadetreino',
            name='exercicios',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='fichadetreino',
            name='usuario',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='ficha_de_treino', to=settings.AUTH_USER_MODEL),
        ),
    ]
